'use client'

import { useEffect, useMemo, useState } from 'react'
import Shell from '../../components/Shell'
import CompanyScopeBar from '../../components/CompanyScopeBar'
import { Badge, Panel, StatCard } from '../../components/Ui'
import { AlertTriangle, CheckCircle2, ClipboardCheck, Clock3, Download, Eye, FileCheck2, Flame, Plus, Search, ShieldCheck, X } from 'lucide-react'
import { DEFAULT_COMPANY_FILTERS, filteredCompanies } from '../../lib/company-master'
import { dbSelect, dbUpdate, dbUpsert, getStoredProfile, isSupabaseConfigured } from '../../lib/supabase-rest'
import styles from './permit-to-work.module.css'

const FORMS={
'Hot Work':{code:'KPNPLT-FORM-SST-008.01',label:'Izin Kerja Panas / Hot Work Permit',na:true,workers:4,checks:['Pekerja sudah diberi penjelasan detail mengenai pekerjaan','Pekerja sudah diberi tahu bahaya yang dapat terjadi','Alat dan material kerja sudah diperiksa kelayakan dan keamanannya','Bahan/material mudah terbakar sudah disingkirkan dari area pekerjaan','Safety sign & barricade line sudah dipasang','Pekerjaan tidak dilakukan seorang diri','Fire watch tersedia','Proteksi paparan panas dan percikan api telah dilakukan','Tabung bertekanan berdiri dan terikat','Flashback arrestor/safety valve terpasang baik','Kunci buka/tutup gas berada di sekitar tabung','Tabung, regulator, selang dan peralatan tidak terkontaminasi oli/minyak','Tabung bertekanan terlindung dari matahari langsung','Sirkulasi udara baik','Safety cover gerinda terpasang baik','Area pengelasan listrik bersih dari air','Kabel massa terpasang baik saat welding','Fire blanket dan fire extinguisher tersedia','Pekerja menggunakan APD yang disyaratkan','APD digunakan dengan benar','Arah angin telah diperhitungkan'],tools:['Tabung Bertekanan','Mesin Las Listrik','Mesin Las Diesel','Gerinda tangan','Gerinda cutting','Cutting Torch'],ppe:['Helmet','Safety Shoes','Ear Plug','Dust Mask','Apron','Safety Glasses','Face Shield']},
'Confined Space':{code:'KPNPLT-FORM-SST-008.02',label:'Izin Kerja Ruang Terbatas / Confined Space Work Permit',na:false,workers:4,checks:['Pekerja sudah diberi penjelasan detail mengenai pekerjaan','Pekerja sudah diberi tahu bahaya yang dapat terjadi','APD/PPE sudah dicek, tidak rusak dan siap pakai','Ruang/tanki telah dipasang exhaust fan/blower selama 2 hari kontinu','Saluran instalasi pipa/sumber energi sudah tertutup','Lokasi dibersihkan/dibilas dan ventilasi kontinu tersedia','Penerangan memadai dengan arus DC 12 volt','Area kerja telah diisolasi dengan pengaman/rambu','Alat komunikasi tersedia','Pekerjaan minimal 2 orang dan 1 orang standby di luar','Tidak menggunakan bahan kimia berbahaya','Alat penyelamatan darurat tersedia'],tools:['Scaffolding Besi','Scaffolding Kayu','Tangga Besi','Tangga Kayu','Mesin Las','Kompressor'],ppe:['Helmet','Safety Shoes','Ear Plug/Muff','Dust Mask','Safety Harness','Safety Glasses','Safety Gloves']},
'Working at Height':{code:'KPNPLT-FORM-SST-008.03',label:'Izin Kerja di Ketinggian / Working at Height Permit',na:true,workers:5,checks:['Pekerja sudah diberi penjelasan detail mengenai pekerjaan','Pekerja sudah diberi tahu bahaya yang dapat terjadi','APD/PPE sudah dicek, tidak rusak dan siap pakai','Pekerja sudah diberi tahu kewajiban memakai APD','Pekerja sudah diberitahu cara menggunakan APD','Safety sign dan barricade line dipasang di bawah area kerja','Akses kerja di ketinggian tersedia dan aman','Akses jalan mempunyai pagar pengaman','Lantai kerja aman tersedia','Area kerja diamankan dari sumber bahaya lain','Sistem pengaman jatuh terpasang bila diperlukan'],tools:['Scaffolding Besi','Scaffolding Kayu','Tangga Besi','Tangga Kayu','Mesin Las','Kompressor'],ppe:['Helmet','Safety Shoes','Ear Plug/Muff','Dust Mask','Full Body Harness','Safety Glasses','Safety Gloves']},
'Electrical Work':{code:'KPNPLT-FORM-SST-008.04',label:'Izin Kerja Listrik / Electrical Work Permit',na:true,workers:4,checks:['Pekerja sudah diberi penjelasan detail mengenai pekerjaan','Pekerja sudah diberi tahu bahaya yang dapat terjadi','Alat dan material kerja sudah diperiksa kelayakan dan keamanannya','Material yang mengganggu pekerjaan sudah disingkirkan','Sumber listrik sudah Lock Out dan Tag Out','Pekerjaan tidak dilakukan seorang diri','Sirkulasi udara baik','Fire blanket dan fire extinguisher tersedia','Pekerja menggunakan APD yang disyaratkan','APD digunakan dengan benar'],tools:['Scaffolding Besi','Scaffolding Kayu','Tangga Besi','Tangga Kayu','Peralatan tangan'],ppe:['Helmet','Safety Glasses','Ear Plug','Dust Mask','Full body harness','Safety Gloves','Safety Shoes']},
'Water Depth Area':{code:'KPNPLT-FORM-SST-008.05',label:'Izin Kerja di Area Kedalaman Air / Work Permit in Water Depth Areas',na:true,workers:5,checks:['Lantai kerja, pegangan tangan dan pengaman lain telah diperiksa','Karyawan yang terlibat dapat berenang','Karyawan tidak memiliki trauma air atau alergi air','Alat pengapung tersedia dan telah diperiksa','Life jacket tersedia 110% dari jumlah pekerja dan telah diperiksa','Komunikasi 2 arah pekerja dan pengawas mencukupi','Semua pekerja sudah disosialisasikan prosedur kerja aman','Kondisi air/arus sudah dipertimbangkan risikonya','Penerangan kerja tersedia dan mencukupi'],tools:['Pompa','Ban pengapung'],ppe:['Helmet','Safety Shoes','Ear Plug','Dust Mask','Life jacket','Safety Glasses','Safety Gloves']}}

const today=()=>new Date().toISOString().slice(0,10)
const mkChecks=t=>FORMS[t].checks.map((q,i)=>({no:i+1,label:q,answer:'',remarks:''}))
const mkMap=a=>Object.fromEntries(a.map(x=>[x,false]))
const empty=(type='Hot Work')=>({id:'',companyCode:'ACP',type,formCode:FORMS[type].code,title:'',unit:'',area:'',requester:'',contractor:'',supervisor:'',startDate:today(),startTime:'08:00',endDate:today(),endTime:'17:00',risk:'High',status:'Draft',jsaNo:'',description:'',workers:Array(FORMS[type].workers).fill(''),checklist:mkChecks(type),equipment:mkMap(FORMS[type].tools),ppe:mkMap(FORMS[type].ppe),environmentNotes:'',gasTest:{lel:'',co:'',oxygen:'',h2s:'',temperature:''},applicantName:'',assistantReviewer:'',ak3Reviewer:'',approverName:'',closure:{date:'',time:'',safe:false,ak3:'',assistant:'',notes:''}})
const dt=v=>{if(!v)return{date:'',time:''};const d=new Date(v),p=n=>String(n).padStart(2,'0');return{date:`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`,time:`${p(d.getHours())}:${p(d.getMinutes())}`}}
const iso=(d,t)=>new Date(`${d}T${t||'00:00'}:00`).toISOString()
const fromDb=r=>{const s=dt(r.start_at),e=dt(r.end_at),type=FORMS[r.permit_type]?r.permit_type:'Hot Work',cfg=FORMS[type];return{id:r.id,companyCode:r.company_code||'',type,formCode:r.form_code||cfg.code,title:r.title||'',unit:r.unit||'',area:r.area||'',requester:r.requester||'',contractor:r.contractor||'',supervisor:r.supervisor||'',startDate:s.date,startTime:s.time,endDate:e.date,endTime:e.time,risk:r.risk||'High',status:r.status||'Draft',jsaNo:r.jsa_no||'',description:r.description||'',workers:Array.isArray(r.workers)?r.workers:[],checklist:Array.isArray(r.safety_checklist)&&r.safety_checklist.length?r.safety_checklist:mkChecks(type),equipment:r.equipment||mkMap(cfg.tools),ppe:r.ppe||mkMap(cfg.ppe),environmentNotes:r.environment_notes||'',gasTest:r.gas_test||{},applicantName:r.applicant_name||'',assistantReviewer:r.assistant_reviewer||'',ak3Reviewer:r.ak3_reviewer||'',approverName:r.approver_name||'',closure:r.closure||{}}}
const gasOk=g=>{const a=[+g.lel,+g.co,+g.oxygen,+g.h2s,+g.temperature];return a.every(Number.isFinite)&&a[0]<=2&&a[1]<=30&&a[2]>=19.5&&a[2]<=23&&a[3]<=10&&a[4]<=35}
const ready=f=>f.checklist.length&&f.checklist.every(x=>x.answer==='Yes'||(FORMS[f.type].na&&x.answer==='N/A'))&&!f.checklist.some(x=>x.answer==='No')
const duration=f=>(new Date(`${f.endDate}T${f.endTime}:00`)-new Date(`${f.startDate}T${f.startTime}:00`))/36e5
const leadHours=f=>(new Date(`${f.startDate}T${f.startTime}:00`)-new Date())/36e5
const tone=v=>['Active','Approved','Closed','Low'].includes(v)?'green':['Submitted','Assistant Review','HSE Review','Suspended','Medium'].includes(v)?'orange':['Rejected','Critical'].includes(v)?'red':'blue'
const fmt=v=>v?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${v}T00:00:00`)):'-'
const toDb=f=>({id:f.id,company_code:f.companyCode,permit_type:f.type,form_code:f.formCodeECB1‰C!#Àá–