'use client'

import Link from 'next/link'
import { useEffect,useMemo,useState } from 'react'
import Shell from '../../components/Shell'
import { Badge,Panel,StatCard } from '../../components/Ui'
import { Activity,BrainCircuit,Building2,CheckCircle2,Database,Link2,ShieldCheck } from 'lucide-react'
import { dbSelect } from '../../lib/supabase-rest'
import { PROJECTED_NOTE,companyOf,esgScores,loadIntelligence } from '../../lib/intelligence-engine'
import styles from '../intelligence-2028.module.css'

const roadmap=[
 {name:'AI Prediction',href:'/ai-prediction',projected:true},{name:'AI Recommendation',href:'/ai-recommendation',projected:true},{name:'ESG Dashboard',href:'/esg-dashboard',projected:true},{name:'GIS',href:'/gis-map',projected:true},{name:'QR Inspection',href:'/qr-inspection',projected:true},{name:'Enterprise Dashboard',href:'/enterprise-dashboard',projected:true},{name:'AI Compliance Prediction',href:'/ai-compliance-prediction',projected:true},{name:'Predictive Inspection',href:'/predictive-inspection',projected:true},{name:'Asset Integrity Analytics',href:'/asset-integrity-analytics',projected:true},
]
export default function EnterpriseDashboard(){
 const[data,setData]=useState(null),[readiness,setReadiness]=useState([])
 useEffect(()=>{loadIntelligence().then(setData);dbSelect('permit_integration_readiness','select=*&order=id.desc').then(setReadiness).catch(()=>setReadiness([]))},[])
 const metrics=useMemo(()=>{if(!data)return{records:0,companies:0,activeModules:0,esg:null};const values=Object.values(data),records=values.reduce((s,v)=>s+(v?.length||0),0),companies=new Set(values.flat().map(companyOf).filter(x=>x&&x!=='UNASSIGNED')).size,activeModules=values.filter(v=>v?.length).length;return{records,companies,activeModules,esg:esgScores(data).overall}},[data])
 const sources=useMemo(()=>data?Object.entries(data).map(([k,v])=>({name:k,count:v?.length||0})).sort((a,b)=>b.count-a.count):[],[data])
 const ptw=useMemo(()=>{const total=readiness.length,jsaGap=readiness.filter(r=>!r.jsa_ready).length,lotoGap=readiness.filter(r=>!r.loto_ready).length,evidenceGap=readiness.filter(r=>!r.evidence_ready).length,ready=readiness.filter(r=>r.jsa_ready&&r.loto_ready&&r.evidence_ready).length;return{total,jsaGap,lotoGap,evidenceGap,ready}},[readiness])
 return <Shell title="Enterprise Dashboard" subtitle="Enterprise Safety Intelligence overview lintas seluruh modul SINSHE 2.0.">
  <div className={styles.note}><BrainCircuit size={17}/><span>{PROJECTED_NOTE}</span></div>
  <div className="stats-grid four"><StatCard label="2028 Roadmap Coverage" value="9/9" hint="semua modul punya route eksplisit" tone="green" icon={<CheckCircle2/>}/><StatCard label="Central Records" value={metrics.records.toLocaleString('id-ID')} hint="across intelligence sources" tone="blue" icon={<Database/>}/><StatCard label="Companies with Data" value={metrics.companies} hint="identified in central data" tone="green" icon={<Building2/>}/><StatCard label="Live Source Modules" value={metrics.activeModules} hint="source tables with records" tone="blue" icon={<Activity/>}/></div>
  <Panel title="Enterprise Safety Intelligence 2028" action="Roadmap modules" className="mt"><div className={styles.grid3}>{roadmap.map(m=><Link key={m.name} href={m.href} className={styles.card} style={{textDecoration:'none',color:'inherit'}}><span>2028 Module</span><b style={{fontSize:15}}>{m.name}</b><small>{m.projected?'* Proyeksi Berdasarkan Analisis Penulis':'Live module'}</small><div style={{marginTop:8}}><Badge tone="green">AVAILABLE</Badge></div></Link>)}</div></Panel>
  <Panel title="Cross-Module Integrity — PTW → JSA → LOTO → Evidence" action={`${ptw.total} permit`} className="mt"><div className={styles.grid3}><div className={styles.card}><span>Integration Ready</span><b>{ptw.ready}</b><small>JSA approved + LOTO ready + file evidence tersedia.</small></div><div className={styles.card}><span>JSA Integrity Gap</span><b>{ptw.jsaGap}</b><small>Permit tanpa JSA Approved/valid dari PT yang sama.</small></div><div className={styles.card}><span>Evidence Gap</span><b>{ptw.evidenceGap}</b><small>Belum memiliki private file evidence yang terkait record PTW.</small></div></div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><Link href="/permit-to-work"><Badge tone="blue">Open Permit to Work</Badge></Link><Link href="/digital-jsa"><Badge tone="green">Open Digital JSA</Badge></Link><Link href="/document-evidence"><Badge tone="orange">Open Document & Evidence</Badge></Link>{ptw.lotoGap>0&&<Link href="/loto-management"><Badge tone="red">LOTO Gap: {ptw.lotoGap}</Badge></Link>}</div></Panel>
  <div className={styles.grid2} style={{marginTop:14}}><Panel title="Central Data Coverage"><div className={styles.list}>{sources.map(s=><div className={styles.listItem} key={s.name}><div><b>{s.name}</b><small>Supabase central source</small></div><Badge tone={s.count?'green':'blue'}>{s.count.toLocaleString('id-ID')}</Badge></div>)}</div></Panel><Panel title="Enterprise Principles"><div className={styles.list}><div className={styles.listItem}><div><b>People</b><small>Workers, supervisors, HSE and management in one ecosystem.</small></div><ShieldCheck/></div><div className={styles.listItem}><div><b>Process</b><small>Briefing → inspection → risk → action → compliance.</small></div><ShieldCheck/></div><div className={styles.listItem}><div><b>Data</b><small>Centralized, traceable and reusable across modules.</small></div><ShieldCheck/></div><div className={styles.listItem}><div><b>Technology</b><small>Web/mobile, QR, GIS and projected intelligence layer.</small></div><ShieldCheck/></div><div className={styles.listItem}><div><b>Integrity</b><small>Hard gate lintas modul menjaga referensi JSA, LOTO dan evidence tetap valid.</small></div><Link2/></div></div></Panel></div>
 </Shell>
}